### ISSUE TITLE
License the Repository

### ISSUE THREAD

**Issue by zedseven** [mchangrh/NoWhatsNew#3]
It currently doesn't have a license, [which technically means it isn't free and open-source](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license/1721#1721).

**Comment by mchangrh** [comment]
You're the only other contributor, I assume you would prefer MIT + Apache2?

**Comment by zedseven** [comment]
MIT + Apache 2.0 is the convention for Rust — typically I go with MIT alone for other projects.

I'm fine with whatever you prefer, however.

**Comment by mchangrh** [comment]
licenced MIT in https://github.com/mchangrh/NoWhatsNew/commit/d1b897601f1ffcf1ca6b460890dd4b2fa11e8eaf
